services:
  hub:
    image: selenium/hub:4.14
    ports:
    - 4444:4444
   # - 4442:4442
   # - 4443:4443
  chrome:
    image: selenium/node-chrome:129.0
    shm_size: '2g'
    depends_on:
    - hub
    environment:
    - SE_EVENT_BUS_HOST=hub
    - SE_EVENT_BUS_PUBLISH_PORT=4442
    - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    - SE_NODE_OVERRIDE_MAX_SESSIONS=true
    - SE_NODE_MAX_SESSIONS=4
  firefox:
    image: selenium/node-firefox:130.0
    
    shm_size: '2g'
    depends_on:
    - hub
    environment:
    - SE_EVENT_BUS_HOST=hub
    - SE_EVENT_BUS_PUBLISH_PORT=4442
    - SE_EVENT_BUS_SUBSCRIBE_PORT=4443  
    - SE_NODE_OVERRIDE_MAX_SESSIONS=true
    - SE_NODE_MAX_SESSIONS=4
  vendor-portal:
    image: pramesh11/myprojectimage_oct24
    depends_on:
    - chrome
    environment:
    - BROWSER=chrome
    - HUB_HOST=hub
    - THREAD_COUNT=3
    - TEST_SUITE=vendorportal.xml
    volumes:
    - C:/Users/prame/DockerWorkspace/05-Running-Tests-Inside-Docker/02-Grid_and_TestSuite/output/vendorportal:/home/MyProject/test-output
  flight-registration:
    image: pramesh11/myprojectimage_oct24
    depends_on:
    - firefox
    environment:
    - BROWSER=firefox
    - HUB_HOST=hub
    - THREAD_COUNT=4
    - TEST_SUITE=flightregistration.xml
    volumes:
    - C:/Users/prame/DockerWorkspace/05-Running-Tests-Inside-Docker/02-Grid_and_TestSuite/output/flightregistration:/home/MyProject/test-output  